site_name: Stellar
site_url: https://znotfireman.github.io/stellar/
theme:
    name: material
nav:
    - Home: index.md
    - About: pls.md
extra:
    version:
        provider: mike
plugins:
    - mike:
        alias_type: symlink
        redirect_template: null
        deploy_prefix: ''
        canonical_version: null
        version_selector: true
        css_dir: css
        javascript_dir: js