call_parentheses = "Input"
collapse_simple_statement = "Never"
column_width = 120
indent_type = "Tabs"
indent_width = 4
line_endings = "Unix"
quote_style = "ForceDouble"

[sort_requires]
	enabled = true
